# TODO: research healthcheck, what it is, and how to use. (from what I gather, it's useful as a condition inside depents_on)
services:
  ms-books-app:
    image: $DOCKER_HUB_USER/testing-ms-books:latest
    build: .
    depends_on:
      - mysqldb
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_HOST_PORT:$PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_LOCAL_PORT
    stdin_open: true
    tty: true

  mysqldb:
    image: mysql:8.3
    container_name: mysqlcontainer
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - db:/var/lib/mysql

volumes:
  db:
